server:
  port: 8002
spring:
  application:
    name: c-auth-project
  cloud:
    nacos:
      discovery:
        # 共享配置的DataId，多个使用,分隔
        # 越靠后，优先级越高；
        # .yaml后缀不能少，只支持yaml/properties
        #        shared-dataids: common.yaml         ### 共享配置
        #        refreshable-dataids: common.yaml    ### 可刷新共享配置
        server-addr: 127.0.0.1:8848    ### nacos server地址
#        file-extension: yaml                ### dataId扩展名
#        namespace: 9a6a7388-eab2-4452-90cb-97f8c7043d05  #命名空间 代指某个环境
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true